// Список услуг
export const serviceList = [
    "Select a service",
    "(Grant) Proposal editing",
    "(Grant) Proposal review",
    "(PhD) Application support",
    "Copy editing",
    "Copy writing ",
    "CV support",
    "Data collection support",
    "Data management",
    "Data sharing support",
    "Data visualisation",
    "Figure editing",
    "Indexing services",
    "Journal guidance",
    "Language editing",
    "Literature search",
    "Manuscript review",
    "Manuscript writing support",
    "OA book funding service",
    "Post editing after Machine Translation",
    "Promotion services",
    "Publication support",
    "Research mentor",
    "Rights and permissions",
    "Scientific editing",
    "Statistical and data analysis",
    "Statistical review",
    "Study design",
    "Submission service",
    "Thesis services",
    "Translation services",
    "Transliteration",
    "Video and graphical abstracts",
    "Workshop/training",
    "Other"
];

export const serviceListRu = [
    // "(Grant) Proposal editing", // редактирование предложения? содержания?
    // "(Grant) Proposal review", // проверка содержания?
    "Помощь с приложением",
    // "Copy editing",
    "Копирайтинг",
    "Написание резюме",
    "Помощь в сборе данных",
    "Управление данными",
    "Помощь в распределении данных",
    "Визуализация данных",
    "Редактирование рисунков",
    "Индексирование сервисов",
    "Руководство журнала",
    "Проверка языка",
    "Поиск литературы",
    "Обзор манускрипта",
    "Помощь в написании манускрипта",
    // "OA book funding service",
    "Редактирование после машинного перевода",
    // "Promotion services",
    "Помощь в публикации",
    "Ментор при поиске",
    "Права и доступ",
    "Научное редактирование",
    "Статистика и анализ данных",
    "Проверка статисктики",
    // "Study design",
    // "Submission service",
    "Работа над тезисом",
    "Работа над переводом",
    "Транслитерация",
    "Графические и видео абстракции",
    "Семинар/тренинг",
    "Другое"
];

// Список предметных областей
export const subjectList = [
    "Select a subject area",
    "Health Sciences",
    "Medicine and Dentistry",
    "Nursing and Health Professions",
    "Pharmacology, Toxicology and Pharmaceutical Science",
    "Veterinary Science and Veterinary Medicine",
    "Life Sciences",
    "Agricultural and Biological Sciences",
    "Biochemistry, Genetics and Molecular Biology",
    "Environmental Science",
    "Immunology and Microbiology",
    "Neuroscience",
    "Physical Sciences",
    "Chemical Engineering",
    "Chemistry",
    "Computer Science",
    "Earth and Planetary Sciences",
    "Energy",
    "Engineering",
    "Materials Science",
    "Mathematics",
    "Physics and Astronomy",
    "Social Sciences and Humanities",
    "Arts and Humanities",
    "Business, Management and Accounting",
    "Decision Sciences",
    "Economics, Econometrics and Finance",
    "Psychology",
    "Social Sciences"
];

export const subjectListRu = [
    "Здоровье",
    "Медицина и стоматология",
    "Уход за больными",
    "Фармакология, токсикология и фармацевтика",
    "Ветеринарная наука и медицина",
    "Наука о жизни",
    "Сельскохозяйственные и биологические науки",
    "Биохимия, генетика и молекулярная биология",
    "Наука об окружающей среде",
    "Иммунология и микробиология",
    "Неврология",
    "Физические науки",
    "Химическая инженерия",
    "Химия",
    "Информатика",
    "Науки о Земле и планетах",
    "Энергия",
    "Инженерное дело",
    "Материаловедение",
    "Математика",
    "Физика и астрономия",
    "Социальные и гуманитарные науки",
    "Искусство и гуманитарные науки",
    "Бизнес, менеджмент и бухгалтерский учет",
    "Науки о принятии решений",
    "Экономика, эконометрика и финансы",
    "Психология",
    "Социальные науки"
];
